### PR TITLE
fix: Upgrade yargs to fix security issue and more

### LINKED ISSUE #10: Refactor error handling
- Handle more errors? Less?
- Improve error handling methods?

### PR DESCRIPTION
**Pull request by danez**
- update yargs because of https://www.npmjs.com/advisories/1500
- Use yargs itself to validate args instead of custom code. Gives nice `--help` and nice errors.
- replace glob with fast-glob which has promise support and should be faster
- update csvtojson to version 2 which now also has promise support and is 8-10x faster (according to changelog)
- change error handling slightly 
  - error if no reports were found.
  - global catch clause to catch all errors that might happen
  - above removes the need to have try-catch

Fixes #10 ?

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -110,23 +96,20 @@ const convertFileRows = (rows) => rows
 const convertAllFileRows = (allFileRows) => allFileRows.map(convertFileRows);
 
 const concatAllFileRows = (allFileRows) => allFileRows
-  .reduce((combined, fileRows) => combined.concat(fileRows));
+  .reduce((combined, fileRows) => combined.concat(fileRows), []);
```
Comment (danez) [inline index.js:99]: This did throw if there are no rows found, hence the initial value.

**Comment by galvarez421** [comment]
Thank you for the contribution! It looks good from reading through it. I will review and test and hopefully merge and release updated package by this weekend.
